### ISSUE TITLE
Add support for sugared syntax a la andReturnNull()

### ISSUE THREAD

**Issue by SpazzMarticus** [psalm/psalm-plugin-mockery#6]
Mockery provides syntax sugar for common return values:

- `andReturnSelf()`
- `andReturnNull()`
- `andReturnFalse()`
- `andReturnTrue()`

Please add this to the psalm plugin, in order to better support mockery.

**Comment by mr-feek** [comment]
I just ran into this too. I'll try to get a pr in the next few days if i get a chance

**Comment by matiux** [comment]
Same problem

**Comment by mr-feek** [comment]
got a pr open ^^^ feel free to check it out
